project:
  type: book
  output-dir: docs

book:
  title: "Data"
  author: "FURao"
  date: "2025/8/5"
  chapters:
    - index.qmd
    - 01metrics.qmd
    - 03data_analysis.qmd
    - 02ABTest.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc-depth: 6
    toc-expand: 2
    link-citations: true
  pdf:
    documentclass: scrreprt

editor: visual

